### ISSUE TITLE
[MIG-326] Rebase and branch on Velero 1.5.x and test for MTC 1.4.0

### ISSUE THREAD

**Issue by eriknelson** [fusor/velero#78]
@shubham-pampattiwar think you'll be able to help @sseago  get this rebased and tested for 1.4.0?

Scott, I'm also not sure entirely what goes into this process if you want to describe that here.

**Comment by shubham-pampattiwar** [comment]
@eriknelson surely I can help test this once @sseago is done with the rebase. I am planning to run the QE end to end test suite.

**Comment by eriknelson** [comment]
Great, thank you!

**Comment by sseago** [comment]
Closing stale issue. This was done prior to MTC 1.4.0 release.
